PersonalWebApp/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PersonalWebApp.Controllers
{
    public class NewsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PersonalWebApp/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebApp.Models.Files;
using PersonalWebApp.Models.Profiles;
using PersonalWebApp.Models.Users;

namespace PersonalWebApp.Controllers
{
    public class ProfileController : Controller
    {
        private UserDbContext _userDb;

        private FileDbContext _fileDb;
        
        private ProfileDbContext _profileDb;

        private IWebHostEnvironment _webHostEnvironment;

        public ProfileController(UserDbContext userDb, FileDbContext fileDb, ProfileDbContext
            profileDb, IWebHostEnvironment webHostEnvironmentl)
        {
            _userDb = userDb;
            _fileDb = fileDb;
            _profileDb = profileDb;
            _webHostEnvironment = webHostEnvironmentl;

            FileDownloader.FileDb = _fileDb;
        }

        public async Task<IActionResult> Index(string name)
        {
            Profile? profile = await ProfileDisplay.Display(name, _profileDb, _userDb);
            if(profile == null)
            {
                return NotFound();
            }
            else
            {
                return View(profile);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            Profile? profile = await ProfileDisplay.Display(User.Identity.Name, _profileDb, _userDb);
            if(profile == null)
            {
                return Unauthorized();
            }
            else
            {
                return View(profile);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProfileEditor editor)
        {
            await ProfileEditor.Edit(await UserDisplay.Display(User.Identity.Name, _userDb), editor, _webHostEnvironment, _fileDb, _profileDb);
            Profile? profile = await ProfileDisplay.Display(User.Identity.Name, _profileDb, _userDb);
            if(profile == null)
            {
                return Unauthorized();
            }
            else
            {
                return View(profile);
            }
        }
    }
}

PersonalWebApp/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PersonalWebApp.Controllers
{
    public class ProjectsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PersonalWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" type="text/css" href="~/CSS/MainStyle.css"/>
        <link rel="stylesheet" type="text/css" href="~/PersonalWebApp.styles.css"/>
        <title>Personal WebApp | @ViewBag.Title</title>
    </head>
    <body>
        <div class="header">
            <div class="invisible">
                <a class="abutton @ViewBag.HomeHeader" href="@Url.Action("Index", "Home")">Home</a>
                <a class="abutton @ViewBag.NewsHeader" href="@Url.Action("Index", "News")">News</a>
                <a class="abutton @ViewBag.ProjectsHeader" href="@Url.Action("Index", "Projects")">
                    Projects</a>
            </div>
            
                @if(User.Identity.IsAuthenticated)
                {
                    <div class="dropdown" id="divuser">
                        <div class="dropdown-head">
                            @User.Identity.Name
                        </div>
                        <div class="dropdown-content">
                            <a class="auser" href="@Url.Action("Edit", "Account")">Edit account</a>
                            <a class="auser" href="@Url.Action("Index", "Profile", new {name = User.Identity.Name})">Profile</a>
                            <a class="auser" href="@Url.Action("Edit", "Profile")">Edit profile</a>
                            <a class="auser" href="@Url.Action("LogOut", "Account")">Log Out</a>
                        </div>
                    </div>
                }
                else
                {
                    <div class="invisible" id="divuser">
                        <a class="abutton auser @ViewBag.RegisterUserHeader"
                            href="@Url.Action("Register", "Account")">Register</a>
                        <a class="abutton auser @ViewBag.LoginUserHeader"
                            href="@Url.Action("SignIn", "Account")">Sign In</a>
                    </div>
                }
        </div>
        <div class="article">@RenderBody()</div>
        <div class="footer">Footer.</div>
    </body>
</html>